### ISSUE TITLE
Replace intro/excerpt with a bit of social proof?

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/website#117]
The intro/excerpt below the image is redundant and a bit empty. It'd be good if we could replace it with some kind of social proof.  Something like this...

> ODK has helped tens of thousands of organizations collect billions of forms and surveys. Users include Google, New York City, Red Cross, Kiva, Carter Center, USAID, WHO, CDC, Jane Goodall Institute, and many others. From election monitoring to tracking outbreaks, ODK tools are the de-facto standard for data collection.

**Comment by adammichaelwood** [comment]
Will do.
