### ISSUE TITLE
Improve local install/build instructions in the README

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/website#122]
Specifically, add a suggestion to use rbenv.

**Comment by yanokwa** [comment]
It might be easier to point people to https://www.ruby-lang.org/en/downloads/ and then say if you are using *nix, use your package manager and rbenv. If you are using macOS, use brew and rbenv. If you are using windows, use RubyInstaller.

**Comment by afparsons** [comment]
@opendatakit-bot claim
