### ISSUE TITLE
Optionally set up Google Analytics

### ISSUE THREAD

**Issue by downeym** [opendatakit/website#2]
In `_config.yml` there is a placeholder for Google Analytics. If planning to set up/continue analytics of website traffic, tracking ID needs updated.

**Comment by yanokwa** [comment]
@opendatakit-bot claim

**Comment by yanokwa** [comment]
@opendatakit-bot claim

**Comment by downeym** [comment]
There is currently GA tracking code in the existing web site.

1. If this issue is not addressed before go-live, there may be gaps in the data if it tracking is re-instated.
2. Who is the caretaker/owner of the GA account currently?
