### ISSUE TITLE
Review data for past blog authors

### ISSUE THREAD

**Issue by downeym** [opendatakit/website#25]
I filled out the data at https://github.com/opendatakit/website/blob/master/_data/authors.yml reflecting authors of past blog posts, and using publicly-available data sources.

Someone ought to review the existing entries and reach out to the authors to let them know there's an opportunity to change their data.

The metadata from this file only shows in the sidebar on blog type posts where the author is specified in the top matter above the content.  (If there is no author data specified in the file, generic ODK information will be shown on the rendered page.)

**Comment by danbjoseph** [comment]
hi folks, you all have data in the blog post authors list, are you happy with what's currently there?

@yanokwa - some people also have `location`
@lognaturel - you have all 7 of the fields that someone uses!
@wbrunette - some people also have `twitter`, and `uri`
@chartung - some people also have  `twitter`, and `uri` (sorry for the double ping, also via email)
@mitchellsundt - some people also have `bio`, `twitter`, and `uri`(sorry for the double ping, also via email)

**Comment by jbeorse** [comment]
Regarding @mitchellsundt, he retired last fall. If you look at his Github activity you can see a hard stop in October. It was my impression that when he left it was a true retirement, at least for now. This is reflected on his [linked in](https://www.linkedin.com/in/mitchellsundt/). I doubt you'll get a response via his old email; I believe he closed that account.

To my knowledge there is no appropriate URI for him, and I would be quite surprised to hear he has a twitter. It seems most appropriate to me to leave his bio blank as well if there is no response from him. Or if something is necessary maybe make it reflect that he's retired. What are your opinions @wbrunette  and @clarlars?

**Comment by clarlars** [comment]
I also have the same understanding as @jbeorse regarding @mitchellsundt.  I would say if you can get a hold of him, then include him otherwise leaving the bio blank makes sense.

**Comment by yanokwa** [comment]
Fixed.
