### ISSUE TITLE
Validate photo/image licenses

### ISSUE THREAD

**Issue by downeym** [opendatakit/website#3]
Need to make sure that any & all photos or images used have an appropriate license/release by photographer. This has not yet been done. If wishing to use the illustrations existing in the prototype, @downeym can provide licenses.

**Comment by downeym** [comment]
@opendatakit-bot claim

**Comment by downeym** [comment]
Dropped in exact copy of replacement licensed images at d4f36ea9df75bb064cdc07040931dbf258526cfc (nothing to review). Looking for a possible group photo that might work for the home page, will submit a PR for feedback.

**Comment by downeym** [comment]
@opendatakit/website How do folks feel about this illustration to replace the "community" photo at the bottom of the home page? At least in the short term until we can get some clearances for ODK community photos. 😄 

![network](https://user-images.githubusercontent.com/841003/38144511-dd15a65e-33f9-11e8-8121-c26d73b1d20e.png)

**Comment by yanokwa** [comment]
I think it's pretty good for now. I'd probably just color in the icons so it's not distracting.

**Comment by downeym** [comment]
SGTM. I've got the vector images so can do that a bit later.

**Comment by yanokwa** [comment]
I believe this has been resolved. @downeym Can you confirm?

**Comment by downeym** [comment]
Yes, as far as I know everything is good to go!
