### ISSUE TITLE
migrate an missing ODK 2 binaries

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/website#31]

**Comment by downeym** [comment]
@wbrunette Any additional description here? Does this mean migrating the binaries to GitHub and then linking them into the site? Or maybe something else that isn't coming to my mind?

**Comment by wbrunette** [comment]
I am putting the latest binaries (the two sets missing from the website) on GitHub then providing links to them. As of right now that is version 2.0.3 and yesterday's release version 2.0.4.

I could also put older versions there too. I wonder how GitHub would order that if a release is older.

**Comment by downeym** [comment]
Perhaps @yanokwa has experience with release ordering?

**Comment by yanokwa** [comment]
@wbrunette After doing this with the ODK binaries, I think it's going to be annoying to publish the releases in three places (Github, forum, and then the website). 

My recommendation is to follow what I did with https://github.com/opendatakit/website/pull/50 and provide a little bit of context and link to the releases page. I can imagine a future where there is a bit of JS that pulls some more information from GitHub, but for now, a simple link to releases seems adequate.

If you do want to link to the latest release, then just add /latest. So for example, https://github.com/opendatakit/collect/releases/latest
