### ISSUE TITLE
Purpose of ODK and ODK community is unclear from highest-impact headings

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/website#34]
Neither "Technology that’s about people" nor "Open Data Kit builds free and open source tools to help organizations magnify human resources through mobile technology" say very much about what ODK is for or who it can help. Providing more information with those highest-impact headings is more likely to draw new community members in.

Please discuss proposed changes at #22.

**Comment by yanokwa** [comment]
Closed by #116
