### ISSUE TITLE
Remove "Other ODK 1 Tools"

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/website#37]
I would like to remove the following tools from the downloads page for now.
* ODK CSVConverter
* ODK FormUploader

I'd like to remove these because they haven't been updated or documented. We'll eventually get to it, but it's more confusing to have them than not to have them.

**Comment by downeym** [comment]
Alternatively, perhaps an "unsupported" section and/or sub-page? But yes, the less folks are set up for failure, the better!

**Comment by yanokwa** [comment]
I'd like to do it two phases. First, we remove before launch (this issue), then we file another issue to re-added the ones that might be useful.

**Comment by yanokwa** [comment]
As promised, https://github.com/opendatakit/website/issues/49 is ready if anyone wants to discuss what tools we might want to add.
