### ISSUE TITLE
Make sure xlsform.opendatakit.org works

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/website#38]
A lot of people use http://opendatakit.org/xiframe to convert their XForms. Before launch, it would be good that we ensure the embed works.

**Comment by downeym** [comment]
Currently it seems just an IFRAME to http://82.196.7.170. Is there any way that site (who runs it?) to run under HTTPS?

**Comment by yanokwa** [comment]
It's run by the community (mostly me). https://github.com/opendatakit/xlsform-server/issues/8 is the issue to add HTTPS.

**Comment by yanokwa** [comment]
The xiframe redirect currently doesn't work. We need to do the following...
- [ ] Wrap a quick UI around https://github.com/opendatakit/xlsform-server/issues/9
- [ ] xlsform.opendatakit.org needs to redirect 82.196.7.170
- [ ] Need to get an HTTP cert on https://github.com/opendatakit/xlsform-server
- [ ] Verify that Enketo preview works
