### ISSUE TITLE
Remove unused assets to speed up clone

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/website#40]
Cloning the repo takes a long time and I think that is because there are assets that aren't being used (e.g., odk2). It would be good to have someone programmatically traverse the website and remove assets that aren't being used.

**Comment by wbrunette** [comment]
With the odk2 docs being moved there are probably some there assets there to remove. I will take a look. I think this will be probably a multiple PR item.

Since drupal imported from wordpress, there maybe stuff we from wordpress that is unneeded as well.

**Comment by yanokwa** [comment]
Just want to add that this is important because we use Git LFS bandwidth each time we do a build and that does cost money (small amounts, but it adds up over all projects).
