### ISSUE TITLE
Add page for unsupported tools

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/website#49]
There are some unsupported downloads that we *may* need a page for. This issue is to discuss which tools we would list on that page. 

#### Should probably be unsupported
- [ ] ODK CSVConverter - https://github.com/opendatakit/briefcase/issues/37
- [ ] ODK FormUploader - https://github.com/opendatakit/briefcase/issues/37

#### Should definitely be unsupported
- [x] XLSForm for Windows
   * We now have https://github.com/opendatakit/xlsform-offline which is cross-platform and updatable
- [x] Clear ODK Briefcase Preferences
   * You can clear prefs in the Briefcase CLI and we'll eventually add this in the UI. See https://github.com/opendatakit/briefcase/issues/37
- [x] BreathCounter APK
  * We have docs to demonstrate returning data to an app. We also have https://github.com/opendatakit/counter which is much more recent.

#### Unsupported (according to the WP site)
- [x] UsableServerDiagnosticApp.war
- [x] ODK Manage
- [x] ODK Clinic
- [x] ODK Aggregate v0.9.8.1

**Comment by yanokwa** [comment]
I filed this issue, but I don't think it's relevant. I'd like to close it. Whatcha think, @lognaturel @wbrunette

**Comment by wbrunette** [comment]
I am fine closing it. IMHO, I think the better place for unsupported tools is on github wikis as i view them similar to skunkworks projects that we are not putting front and center.
