### ISSUE TITLE
Remove text about verifying downloads

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/website#59]
Our current downloads infrastructure does not generate SHA256 hashes and I don't think we should be in the business of generating these hashes or asking our users to verify. 

I propose we
- [ ] Remove this text from `_pages/download/index.md`
- [ ] Delete `/assets/signatures.txt`
- [ ] File an issue on https://github.com/opendatakit/docs/issues/new to remove https://docs.opendatakit.org/verify-downloads as well.

What do you think, @wbrunette?

**Comment by wbrunette** [comment]
I am indifferent. I know @clarlars and @jbeorse have stronger opinions about it than me. 

I am not sure we should have a text file that we keep updating without automation (so I am on board removing that)

I think we can just add the SHA to the download text when we post the release. However, maybe we should let people know it's available on the release page on github? 

I going to let others weigh in.

**Comment by clarlars** [comment]
I am probably one of the few people who actually verifies the SHA hashes of downloads, but I like knowing that what I downloaded is the correct version and not an infected binary.  I do know that generating these are a pain and agree that automating the process would be better to remove user error.

**Comment by jbeorse** [comment]
I admit I never check them myself, but I can see their value in protecting against man in the middle issues. I think they provide a sense of security, and an audit trail if anything shows up fishy. 

How difficult is this to add to our downloads structure?

**Comment by yanokwa** [comment]
As far as viruses, it seems more probable that the person generating the build could have a virus. Or the download site, along with the SHA, could be compromised. Case in point, [Transmission](https://www.macrumors.com/2016/03/07/transmission-malware-downloaded-6500-times/) had a virus embedded in the app on the official site.

If most of the core team don't check the hash, then users are definitely not checking the hash. It's not a lot of work, but when it comes to shipping releases, I'd argue it's death by a thousand cuts.

**Comment by jbeorse** [comment]
This isn't a blocker for me. If the consensus is to remove it then I'm fine with it. We can come back to it later if we do find ourselves with a problem.
