### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/website#61]
This is an issue that is never closed.

Links break all the time. If you notice a broken link, please send in a PR.

**Comment by lognaturel** [comment]
There are a number of free tools online that will highlight broken links on a site that would be helpful for this.

Eventually it would be good to have a link checker as part of continuous integration. https://github.com/gjtorikian/html-proofer is an example of such a tool.

**Comment by yanokwa** [comment]
Closing in favor of #100
