### ISSUE TITLE
There is no link to ODK 2 source code

### ISSUE THREAD

**Issue by jbeorse** [opendatakit/website#68]
On the software page there is a link to the ODK 1 source code on github, to https://github.com/opendatakit/opendatakit. This seems appropriate and the correct link. But there is no link to ODK 2 source code.

**Comment by yanokwa** [comment]
I think the link to that repo is probably not a good idea long term. I'd vote for removing it and then linking to the source code of each tool directly on the downloads page. 

For example, on http://staging.opendatakit.org/download/odk2, it'd look something like this:
> Download Tables releases on GitHub [Source code]

**Comment by jbeorse** [comment]
Sure thing. That makes sense. I'll update the PR accordingly.

**Comment by jbeorse** [comment]
Fixed with https://github.com/opendatakit/website/pull/77
