### ISSUE TITLE
"Hire" link shows home page

### ISSUE THREAD

**Issue by akshay-ap** [opendatakit/website#73]
In FAQ, "How do I customize or implement an ODK solution?" there is link on `hire help` which redirects user to `/support/help-for-hire/`.
Currently, redirection succeeds but, it shows home page and has nothing related to customizing ODK.
http://staging.opendatakit.org/support/help-for-hire/

**Comment by akshay-ap** [comment]
In docs, user is redirected to https://opendatakit.org/help/help-for-hire/.
One possible solution can be to copy the content from above link to new file "`website/_pages/about/hire-help`

**Comment by jbeorse** [comment]
Its my understanding that the Help For Hire page is depracated and that the new home for this kind of thing is the Marketplace on the forum: https://forum.opendatakit.org/c/marketplace

I propose this as the solution, and am happy to do it if everyone agrees.

**Comment by yanokwa** [comment]
Fixed by #235
