### ISSUE TITLE
Remove software page and remove unique content to download

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/website#80]
I think there should be a single and obvious place that people have to click to get what they came for and having both a software and download page is confusing.

I think we should remove Software page. Pretty much all the content here is already captured in the docs. And the content that isn't there could pretty easily be moved to download.

**Comment by jbeorse** [comment]
The "Software" name does seem confusing. If we scrap this page we lose our link to the documentation though, as well as the "Additional Documentation" section and "Helpful Links". But the linked issue #21 provides a good new home. I agree with this change if a good "Help" page takes its place,
