### ISSUE TITLE
Remove intra-page link navbar

### ISSUE THREAD

**Issue by smoyth** [opendatakit/website#85]
This site has a lot of navigational elements currently (4 if you are on mobile view (the hamburger, header, side/toggle nav, and intra-page nav)). That is too many!

I think we can do without the intra-page links. If a page has that much content that it needs such links, it could be split, or in extreme cases, have an inline table of contents beneath the page title element.

**Comment by lognaturel** [comment]
I agree with this. It uses valuable horizontal real-estate and I always expect it to take me somewhere else rather than within the page.

**Comment by wbrunette** [comment]
I think this is good suggestion based on the https://github.com/opendatakit/website/issues/87 it causes on the mobile web.

**Comment by yanokwa** [comment]
Fixed by #123
