### ISSUE TITLE
blog images are broken

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/website#97]
See for example:
http://staging.opendatakit.org/2017/06/01/configure-collect-on-many-devices-with-qr-codes/

There are `<img>`s on the page, but the images can't be found
The images ARE in the repo,
but they aren't where Jekyll is looking for them, 
so they don't make it into the build output.

-----

I guess it is only worth fixing this if we're going to keep the blog intact.
Do we have a running convo on that?

**Comment by yanokwa** [comment]
The links to the images are generated dynamically, and that is what the `-123x456` prefix is for. It looks like the crawler that got the HTML got pictures at one size and the crawler that got different sizes. Fun.

**Comment by adammichaelwood** [comment]
I think the right way to fix this issue is to change the `<img>` refs in the post `.md` files to point to the unscaled versions. Those elements also need to have the `height` and `width` attributes removed. (Removing the existing `class` attribute would be good too.)

The CSS on the front will make them fit well at column width. After that, we can discuss resizing (screenshots, for example, are a bit too big).

**Comment by adammichaelwood** [comment]
While we're at it ---
I wouldn't object to removing `/wp-content/uploads/` from the image paths.

-----

I can do this, but someone with better regex skills could probably do it faster than me...
